arm_left_controller:
  type: "posvel_controllers/MybotJointTrajectoryController"
  joints:
    - left_shoulder_joint_0
    - left_shoulder_joint_1
    - left_shoulder_joint_2
    - left_shoulder_joint_3
    - left_elbow_joint_0
    - left_wrist_joint_0
    - left_wrist_joint_1
    - left_wrist_joint_2

  constraints:
    goal_time: 1.0
    stopped_velocity_tolerance: 0.1
    left_shoulder_joint_0:
      trajectory: 0.3               # Not enforced if unspecified
      goal: 0.04                     # Not enforced if unspecified
    left_shoulder_joint_1:
      trajectory: 0.3               # Not enforced if unspecified
      goal: 0.04                     # Not enforced if unspecified
    left_shoulder_joint_2:
      trajectory: 0.3               # Not enforced if unspecified
      goal: 0.04                     # Not enforced if unspecified
    left_shoulder_joint_3:
      trajectory: 0.3               # Not enforced if unspecified
      goal: 0.04                     # Not enforced if unspecified
    left_elbow_joint_0:
      trajectory: 0.3               # Not enforced if unspecified
      goal: 0.04                     # Not enforced if unspecified
    left_wrist_joint_0:
      trajectory: 0.3               # Not enforced if unspecified
      goal: 0.04                     # Not enforced if unspecified
    left_wrist_joint_1:
      trajectory: 0.3               # Not enforced if unspecified
      goal: 0.04                     # Not enforced if unspecified
    left_wrist_joint_2:
      trajectory: 0.3               # Not enforced if unspecified
      goal: 0.04                     # Not enforced if unspecified
  gains:
    left_shoulder_joint_0: {p: 1000.0, d: 250.0, i: 100.0, i_clamp: 4.0}
    left_shoulder_joint_1: {p: 1000.0, d: 250.0, i: 100.0, i_clamp: 4.0}
    left_shoulder_joint_2: {p: 1000.0, d: 250.0, i: 100.0, i_clamp: 4.0}
    left_shoulder_joint_3: {p: 1000.0, d: 250.0, i: 100.0, i_clamp: 4.0}
    left_elbow_joint_0: {p: 1000.0, d: 250.0, i: 100.0, i_clamp: 4.0}
    left_wrist_joint_0: {p: 1000.0, d: 250.0, i: 100.0, i_clamp: 4.0}
    left_wrist_joint_1: {p: 1000.0, d: 250.0, i: 100.0, i_clamp: 4.0}
    left_wrist_joint_2: {p: 1000.0, d: 250.0, i: 100.0, i_clamp: 4.0}

  state_publish_rate:  20            # Override default
  action_monitor_rate: 20            # Override default
  stop_trajectory_duration: 0        # Override default

