bottle_mouth_right_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - right_bottle_mouth_joint_x
    - right_bottle_mouth_joint_y
    - right_bottle_mouth_joint_z


  state_publish_rate:  20            # Override default
  action_monitor_rate: 20            # Override default
  stop_trajectory_duration: 0        # Override default

