gripper_right_controller:
  type: "posvel_controllers/MybotJointTrajectoryController"
  joints:
    - right_gripper_forefinger_joint_0
    - right_gripper_littlefinger_joint_0
    - right_gripper_thumb_joint_0

  gains:
    right_gripper_forefinger_joint_0: {p: 1000.0, d: 250.0, i: 100.0, i_clamp: 4.0}
    right_gripper_littlefinger_joint_0: {p: 1000.0, d: 250.0, i: 100.0, i_clamp: 4.0}
    right_gripper_thumb_joint_0: {p: 1000.0, d: 250.0, i: 100.0, i_clamp: 4.0}

  state_publish_rate:  10            # Override default
  action_monitor_rate: 10            # Override default
  stop_trajectory_duration: 0        # Override default


