head_controller:
  type: "posvel_controllers/MybotJointTrajectoryController"
  joints:
    - head_joint_0
    - head_joint_1
    - head_joint_2
    - head_joint_3

  constraints:
    goal_time: 1.0
    stopped_velocity_tolerance: 0.1
    head_joint_0:
      trajectory: 0.2               # Not enforced if unspecified
      goal: 0.1                     # Not enforced if unspecified
    head_joint_1:
      trajectory: 0.2               # Not enforced if unspecified
      goal: 0.1                     # Not enforced if unspecified
    head_joint_2:
      trajectory: 0.2               # Not enforced if unspecified
      goal: 0.1                     # Not enforced if unspecified
    head_joint_3:
      trajectory: 0.2               # Not enforced if unspecified
      goal: 0.1                     # Not enforced if unspecified

  gains:
    head_joint_0: {p: 1000.0, d: 250.0, i: 100.0, i_clamp: 4.0}
    head_joint_1: {p: 1000.0, d: 250.0, i: 100.0, i_clamp: 4.0}
    head_joint_2: {p: 1000.0, d: 250.0, i: 100.0, i_clamp: 4.0}
    head_joint_3: {p: 1000.0, d: 250.0, i: 100.0, i_clamp: 4.0}

  state_publish_rate:  10            # Override default
  action_monitor_rate: 10            # Override default
  stop_trajectory_duration: 0        # Override default



