torso_controller:
  type: "posvel_controllers/MybotJointTrajectoryController"
  joints:
    - waist_joint_0
    - waist_joint_1

  constraints:
    goal_time: 1.0
    stopped_velocity_tolerance: 0.1

  gains:
    waist_joint_0: {p: 1000.0, d: 250.0, i: 100.0, i_clamp: 4.0}
    waist_joint_1: {p: 1000.0, d: 250.0, i: 100.0, i_clamp: 4.0}

  state_publish_rate:  20            # Override default
  action_monitor_rate: 20            # Override default
  stop_trajectory_duration: 0        # Override default



