DWAPlannerROS:
  # Set the acceleration limits of the robot
  acc_lim_x: 2.5
  acc_lim_y: 2.5
  acc_lim_th: 3.2 

  # Set the velocity limits of the robot
  max_trans_vel: 0.2
  min_trans_vel: -0.2
  max_vel_x: 0.5
  min_vel_x: -0.5
  max_vel_y: 0.5
  min_vel_y: -0.5
  max_rot_vel: 0.5
  min_rot_vel: -0.5

  # Goal Tolerance 
  yaw_goal_tolerance: 0.05
  xy_goal_tolerance: 0.1
  latch_xy_goal_tolerance: true


  # Simulation parameter
  sim_time: 1.7
  sim_granularity: 0.025
  vx_samples: 3
  vy_samples: 3
  vtheta_samples: 20
  penalize_negative_x: false

  path_distance_bias: 30
  goal_distance_bias: 24
  occdist_scale: 0.01
  forward_point_distance: 0.325


  #Eat up the plan as the robot moves along it
  prune_plan: true
