# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  head_joint_0:
    has_velocity_limits: true
    max_velocity: 0.418879020479
    has_acceleration_limits: false
    max_acceleration: 0
  head_joint_1:
    has_velocity_limits: true
    max_velocity: 0.418879020479
    has_acceleration_limits: false
    max_acceleration: 0
  head_joint_2:
    has_velocity_limits: true
    max_velocity: 0.418879020479
    has_acceleration_limits: false
    max_acceleration: 0
  head_joint_3:
    has_velocity_limits: true
    max_velocity: 0.418879020479
    has_acceleration_limits: false
    max_acceleration: 0
  left_bottle_mouth_joint_x:
    has_velocity_limits: true
    max_velocity: 4.18879020479
    has_acceleration_limits: false
    max_acceleration: 0
  left_bottle_mouth_joint_y:
    has_velocity_limits: true
    max_velocity: 4.18879020479
    has_acceleration_limits: false
    max_acceleration: 0
  left_bottle_mouth_joint_z:
    has_velocity_limits: true
    max_velocity: 4.18879020479
    has_acceleration_limits: false
    max_acceleration: 0
  left_elbow_joint_0:
    has_velocity_limits: true
    max_velocity: 0.418879020479
    has_acceleration_limits: false
    max_acceleration: 0
  left_gripper_forefinger_joint_0:
    has_velocity_limits: true
    max_velocity: 0.418879020479
    has_acceleration_limits: false
    max_acceleration: 0
  left_gripper_littlefinger_joint_0:
    has_velocity_limits: true
    max_velocity: 0.418879020479
    has_acceleration_limits: false
    max_acceleration: 0
  left_gripper_thumb_joint_0:
    has_velocity_limits: true
    max_velocity: 0.418879020479
    has_acceleration_limits: false
    max_acceleration: 0
  left_shoulder_joint_0:
    has_velocity_limits: true
    max_velocity: 0.418879020479
    has_acceleration_limits: false
    max_acceleration: 0
  left_shoulder_joint_1:
    has_velocity_limits: true
    max_velocity: 0.418879020479
    has_acceleration_limits: false
    max_acceleration: 0
  left_shoulder_joint_2:
    has_velocity_limits: true
    max_velocity: 0.418879020479
    has_acceleration_limits: false
    max_acceleration: 0
  left_shoulder_joint_3:
    has_velocity_limits: true
    max_velocity: 0.418879020479
    has_acceleration_limits: false
    max_acceleration: 0
  left_wrist_joint_0:
    has_velocity_limits: true
    max_velocity: 0.418879020479
    has_acceleration_limits: false
    max_acceleration: 0
  left_wrist_joint_1:
    has_velocity_limits: true
    max_velocity: 0.418879020479
    has_acceleration_limits: false
    max_acceleration: 0
  left_wrist_joint_2:
    has_velocity_limits: true
    max_velocity: 0.418879020479
    has_acceleration_limits: false
    max_acceleration: 0
  right_bottle_mouth_joint_x:
    has_velocity_limits: true
    max_velocity: 4.18879020479
    has_acceleration_limits: false
    max_acceleration: 0
  right_bottle_mouth_joint_y:
    has_velocity_limits: true
    max_velocity: 4.18879020479
    has_acceleration_limits: false
    max_acceleration: 0
  right_bottle_mouth_joint_z:
    has_velocity_limits: true
    max_velocity: 4.18879020479
    has_acceleration_limits: false
    max_acceleration: 0
  right_elbow_joint_0:
    has_velocity_limits: true
    max_velocity: 0.418879020479
    has_acceleration_limits: false
    max_acceleration: 0
  right_gripper_forefinger_joint_0:
    has_velocity_limits: true
    max_velocity: 0.418879020479
    has_acceleration_limits: false
    max_acceleration: 0
  right_gripper_littlefinger_joint_0:
    has_velocity_limits: true
    max_velocity: 0.418879020479
    has_acceleration_limits: false
    max_acceleration: 0
  right_gripper_thumb_joint_0:
    has_velocity_limits: true
    max_velocity: 0.418879020479
    has_acceleration_limits: false
    max_acceleration: 0
  right_shoulder_joint_0:
    has_velocity_limits: true
    max_velocity: 0.418879020479
    has_acceleration_limits: false
    max_acceleration: 0
  right_shoulder_joint_1:
    has_velocity_limits: true
    max_velocity: 0.418879020479
    has_acceleration_limits: false
    max_acceleration: 0
  right_shoulder_joint_2:
    has_velocity_limits: true
    max_velocity: 0.418879020479
    has_acceleration_limits: false
    max_acceleration: 0
  right_shoulder_joint_3:
    has_velocity_limits: true
    max_velocity: 0.418879020479
    has_acceleration_limits: false
    max_acceleration: 0
  right_wrist_joint_0:
    has_velocity_limits: true
    max_velocity: 0.418879020479
    has_acceleration_limits: false
    max_acceleration: 0
  right_wrist_joint_1:
    has_velocity_limits: true
    max_velocity: 0.418879020479
    has_acceleration_limits: false
    max_acceleration: 0
  right_wrist_joint_2:
    has_velocity_limits: true
    max_velocity: 0.418879020479
    has_acceleration_limits: false
    max_acceleration: 0
  waist_joint_0:
    has_velocity_limits: true
    max_velocity: 0.418879020479
    has_acceleration_limits: false
    max_acceleration: 0
  waist_joint_1:
    has_velocity_limits: true
    max_velocity: 0.418879020479
    has_acceleration_limits: false
    max_acceleration: 0