sensors: 
 - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
   point_cloud_topic: /rgbd_receiver/depth_registered/points
   max_range: 2.0
   point_subsample: 4
   resolution: 0.015
   padding_offset: 0.04 # in cm
   padding_scale: 1.0
   filtered_cloud_topic: filtered_cloud
